import { useEffect, useRef, useState } from 'react'
import { Mic, MicOff, PhoneOff, Radio, Volume2, X } from 'lucide-react'
import { API_URL, api } from '../services/api'
import type { CognitiveState, ToolAction, VoiceEvent } from '../types'
import { Badge } from './Common'
import { BrowserAudioQueue } from '../services/BrowserAudioQueue'

const WS_URL=`${API_URL.replace(/^http/,'ws')}/voice/session`
const LABELS:Record<string,string>={LISTENING:'Ouvindo',TRANSCRIBING:'Transcrevendo',THINKING:'Pensando',SEARCHING_MEMORY:'Buscando memória',SEARCHING_KNOWLEDGE:'Buscando conhecimento',USING_TOOL:'Usando ferramenta',WAITING_CONFIRMATION:'Aguardando confirmação',SPEAKING:'Falando',ERROR:'Erro',IDLE:'Em repouso'}
interface VoiceConfig{echo_cancellation:boolean;noise_suppression:boolean;auto_gain_control:boolean;barge_in_sensitivity:number;silence_end_ms:number}

export function VoiceConversation({conversationId,onClose,onTranscript,onRefresh,onAction}:{conversationId?:string;onClose:()=>void;onTranscript:(text:string)=>void;onRefresh:(conversationId?:string)=>void;onAction:(action:NonNullable<VoiceEvent['action']>)=>void}){
  const[state,setState]=useState<CognitiveState>('IDLE');const[error,setError]=useState('');const[muted,setMuted]=useState(false);const[transcript,setTranscript]=useState('');const[assistant,setAssistant]=useState('');const[active,setActive]=useState(false);const[pushToTalk,setPushToTalk]=useState(false);const[pendingAction,setPendingAction]=useState<ToolAction>()
  const socket=useRef<WebSocket|undefined>(undefined);const media=useRef<MediaStream|undefined>(undefined);const recorder=useRef<MediaRecorder|undefined>(undefined);const chunks=useRef<Blob[]>([]);const context=useRef<AudioContext|undefined>(undefined);const frame=useRef<number|undefined>(undefined);const speech=useRef(false);const lastVoice=useRef(0);const utteranceStart=useRef(0);const currentConversation=useRef(conversationId);const activeRef=useRef(false);const pushToTalkRef=useRef(false);const threshold=useRef(.035);const silenceMs=useRef(900);const audioQueue=useRef<BrowserAudioQueue|undefined>(undefined)

  if(!audioQueue.current)audioQueue.current=new BrowserAudioQueue({started:queue_id=>socket.current?.send(JSON.stringify({type:'playback_started',queue_id})),finished:queue_id=>socket.current?.send(JSON.stringify({type:'playback_finished',queue_id})),interrupted:queue_id=>socket.current?.send(JSON.stringify({type:'playback_interrupted',queue_id})),state:value=>setState(value)})
  const stopPlayback=()=>audioQueue.current?.cancelAll()
  const handleEvent=(event:VoiceEvent)=>{if(event.state)setState(event.state);if(['listening','thinking','speaking'].includes(event.type))setState((event.state||event.type.toUpperCase()) as CognitiveState);if(event.type==='transcript'&&event.text){setTranscript(event.text);onTranscript(event.text)}if(event.type==='assistant_text'){if(event.final){setAssistant(event.text||assistant);onRefresh(currentConversation.current)}else setAssistant(value=>value+(event.text||''))}if(event.type==='thinking'&&event.conversation_id)currentConversation.current=event.conversation_id;if(event.type==='confirmation_required'&&event.action){setPendingAction(event.action);onAction(event.action);setState('WAITING_CONFIRMATION')}if(event.type==='tool_result')setPendingAction(undefined);if(event.type==='tts_chunk')audioQueue.current?.enqueue(event);if(event.type==='error'){setError(`${event.error?.code||'VOICE_SESSION_FAILED'}: ${event.error?.message||'Falha de voz.'}`);setState('ERROR')}}

  const sendRecording=async(blob:Blob)=>{if(!socket.current||socket.current.readyState!==WebSocket.OPEN||blob.size<32)return;socket.current.send(await blob.arrayBuffer())}
  const startRecorder=()=>{if(!media.current||!activeRef.current)return;const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const next=new MediaRecorder(media.current,{mimeType:mime,audioBitsPerSecond:64000});chunks.current=[];speech.current=pushToTalkRef.current;utteranceStart.current=performance.now();next.ondataavailable=event=>{if(event.data.size)chunks.current.push(event.data)};next.onstop=()=>{const hadSpeech=speech.current;const blob=new Blob(chunks.current,{type:mime});speech.current=false;if(hadSpeech)void sendRecording(blob);if(activeRef.current&&!pushToTalkRef.current)setTimeout(startRecorder,180)};next.start(250);recorder.current=next}
  const monitor=(analyser:AnalyserNode)=>{const values=new Uint8Array(analyser.fftSize);const tick=()=>{analyser.getByteTimeDomainData(values);let sum=0;for(const value of values){const normalized=(value-128)/128;sum+=normalized*normalized}const rms=Math.sqrt(sum/values.length);const now=performance.now();if(rms>threshold.current){if(audioQueue.current?.isPlaying){stopPlayback();socket.current?.send(JSON.stringify({type:'interrupt'}))}speech.current=true;lastVoice.current=now}if(!pushToTalkRef.current&&speech.current&&now-lastVoice.current>silenceMs.current&&recorder.current?.state==='recording')recorder.current.stop();if(recorder.current?.state==='recording'&&now-utteranceStart.current>30000)recorder.current.stop();frame.current=requestAnimationFrame(tick)};frame.current=requestAnimationFrame(tick)}
  const start=async()=>{setError('');try{const config=await api<VoiceConfig>('/voice/settings');threshold.current=config.barge_in_sensitivity;silenceMs.current=config.silence_end_ms;const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:config.echo_cancellation,noiseSuppression:config.noise_suppression,autoGainControl:config.auto_gain_control}});media.current=stream;const audioContext=new AudioContext();context.current=audioContext;const source=audioContext.createMediaStreamSource(stream);const analyser=audioContext.createAnalyser();analyser.fftSize=512;source.connect(analyser);const ws=new WebSocket(WS_URL);ws.binaryType='arraybuffer';ws.onopen=()=>{activeRef.current=true;setActive(true);setState('LISTENING');ws.send(JSON.stringify({type:'session_start',conversation_id:conversationId,mime_type:'audio/webm'}));setTimeout(startRecorder,100);monitor(analyser)};ws.onmessage=message=>handleEvent(JSON.parse(String(message.data)) as VoiceEvent);ws.onerror=()=>setError('VOICE_SESSION_FAILED: WebSocket local indisponível.');socket.current=ws}catch(reason){const name=reason instanceof DOMException?reason.name:'';setError(`${name==='NotAllowedError'?'MIC_PERMISSION_DENIED':'MIC_UNAVAILABLE'}: Não foi possível acessar o microfone.`);setState('ERROR')}}
  const stop=()=>{activeRef.current=false;setActive(false);stopPlayback();if(frame.current)cancelAnimationFrame(frame.current);if(recorder.current?.state==='recording')recorder.current.stop();media.current?.getTracks().forEach(track=>track.stop());void context.current?.close();if(socket.current?.readyState===WebSocket.OPEN)socket.current.send(JSON.stringify({type:'session_stop'}));socket.current?.close();setState('IDLE')}
  const toggleMute=()=>{const next=!muted;setMuted(next);media.current?.getAudioTracks().forEach(track=>track.enabled=!next);socket.current?.send(JSON.stringify({type:next?'mute':'unmute'}))}
  useEffect(()=>{void start();return stop},[])
  return <div className="voice-overlay"><section className="voice-session"><button className="icon-button voice-close" onClick={()=>{stop();onClose()}} aria-label="Encerrar conversa"><X/></button><div className={`voice-orb state-${state.toLowerCase()}`}><Radio/></div><span className="eyebrow">CONVERSA LOCAL</span><h2>JARVIS · {LABELS[state]||state}</h2><Badge tone={active?'success':'warning'}>{active?'sessão ativa':'conectando'}</Badge><div className="voice-wave" aria-hidden="true">{[1,2,3,4,5,6,7].map(item=><i key={item}/>)}</div><div className="voice-live-copy"><small>VOCÊ</small><p>{transcript||'Fale quando estiver pronto.'}</p><small>JARVIS</small><p>{assistant||'Aguardando o primeiro turno.'}</p></div>{pendingAction&&<div className="voice-confirmation"><span className="eyebrow">CONFIRMAÇÃO NECESSÁRIA</span><h3>{String(pendingAction.input.title||pendingAction.input.content||pendingAction.tool)}</h3><p>{pendingAction.tool.replaceAll('_',' ')}</p><div><button onClick={()=>socket.current?.send(JSON.stringify({type:'confirmation',approved:false}))}>Cancelar</button><button className="primary" onClick={()=>socket.current?.send(JSON.stringify({type:'confirmation',approved:true}))}>Confirmar</button></div><small>Você também pode dizer “confirmo” ou “cancele”.</small></div>}{error&&<div className="chat-error">{error}<small>O chat textual continua disponível.</small></div>}<div className="voice-controls"><button onClick={toggleMute}>{muted?<MicOff/>:<Mic/>}{muted?'Ativar microfone':'Silenciar'}</button><button onClick={()=>setPushToTalk(value=>{pushToTalkRef.current=!value;return !value})}><Volume2/>{pushToTalk?'Modo contínuo':'Segure para falar'}</button><button className="danger" onClick={()=>{stop();onClose()}}><PhoneOff/>Encerrar conversa</button></div>{pushToTalk&&<button className="push-to-talk" onPointerDown={()=>{speech.current=true;startRecorder()}} onPointerUp={()=>recorder.current?.state==='recording'&&recorder.current.stop()}>SEGURE PARA FALAR</button>}<small>Áudio do microfone é descartado após a transcrição · localhost</small></section></div>
}
