import { useEffect, useState } from 'react'
import { Check, ChevronRight, Upload } from 'lucide-react'
import { api, jsonRequest } from '../../services/api'

interface OnboardingStatus{completed:boolean;user_name:string;backend:string;ollama:string;model_available:boolean;model:string;gpu_detected:boolean;memory_behavior:{mode:string};migration_candidates:Array<{path:string;available:boolean}>;requires_account:boolean;external_transfer:boolean}
const steps=['Backend local','Ollama','Modelo Qwen','GPU','Como chamar você','Comportamento de memória','Importar documentos']

export function StartupIntro(){
  const[visible,setVisible]=useState(false);const[loading,setLoading]=useState(true);const[status,setStatus]=useState<OnboardingStatus>();const[step,setStep]=useState(0);const[name,setName]=useState('');const[memoryMode,setMemoryMode]=useState('suggest');const[uploading,setUploading]=useState(false);const[error,setError]=useState('')
  useEffect(()=>{api<OnboardingStatus>('/onboarding').then(data=>{setStatus(data);setName(data.user_name||'');setMemoryMode(data.memory_behavior?.mode||'suggest');setVisible(!data.completed)}).catch(err=>{setError(err instanceof Error?err.message:String(err));setVisible(true)}).finally(()=>setLoading(false))},[])
  if(loading||!visible)return null
  const checks=[status?.backend==='online',status?.ollama==='online'||status?.ollama==='ok',status?.model_available,status?.gpu_detected]
  const upload=async(file?:File)=>{if(!file)return;setUploading(true);const body=new FormData();body.append('file',file);try{await api('/library',{method:'POST',body})}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setUploading(false)}}
  const finish=async()=>{try{await api('/onboarding/complete',jsonRequest('POST',{user_name:name,memory_mode:memoryMode}));setVisible(false)}catch(err){setError(err instanceof Error?err.message:String(err))}}
  return <div className="startup-overlay onboarding"><div className="onboarding-card"><div className="startup-core online"><i/><i/><i/><div>J</div></div><span className="eyebrow">PRIMEIRA EXECUÇÃO · 100% LOCAL</span><h1>Prepare o Jarvis</h1><p>Nenhuma conta é exigida e nenhum dado é enviado externamente.</p><div className="onboarding-progress">{steps.map((label,index)=><button key={label} className={index===step?'active':index<step?'done':''} onClick={()=>setStep(index)}><span>{index<step?<Check/>:index+1}</span>{label}</button>)}</div><section className="onboarding-step">
    {step<4&&<><h2>{steps[step]}</h2><div className={`check-status ${checks[step]?'ok':'warning'}`}>{checks[step]?<Check/>:null}<strong>{step===0?'Aplicativo online':step===1?`Ollama ${status?.ollama||'indisponível'}`:step===2?`${status?.model||'Qwen'} ${status?.model_available?'disponível':'não encontrado'}`:status?.gpu_detected?'GPU NVIDIA detectada':'GPU não detectada'}</strong></div>{step===1&&!checks[step]&&<p>Você pode continuar e instalar/iniciar o Ollama depois.</p>}</>}
    {step===4&&<><h2>Como o Jarvis chama você?</h2><input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder="Seu nome ou apelido"/></>}
    {step===5&&<><h2>Comportamento de memória</h2><label><input type="radio" checked={memoryMode==='disabled'} onChange={()=>setMemoryMode('disabled')}/>Não sugerir memória</label><label><input type="radio" checked={memoryMode==='suggest'} onChange={()=>setMemoryMode('suggest')}/>Sugerir e sempre pedir confirmação</label><label><input type="radio" checked={memoryMode==='auto'} onChange={()=>setMemoryMode('auto')}/>Salvar automaticamente <small>(não recomendado; permanece desligado por padrão)</small></label></>}
    {step===6&&<><h2>Documentos e dados existentes</h2><label className="onboarding-upload"><Upload/><span>{uploading?'Importando…':'Importar um documento agora'}</span><input type="file" accept=".pdf,.docx,.txt,.md" onChange={event=>void upload(event.target.files?.[0])}/></label><p>Este passo é opcional. O processamento ocorre em segundo plano.</p>{status?.migration_candidates.map(item=><div className="migration-note" key={item.path}><strong>Instalação anterior detectada</strong><small>{item.path}</small><p>Nenhum dado foi copiado. A migração só ocorrerá após sua autorização em Dados.</p></div>)}</>}
  </section>{error&&<div className="chat-error">{error}</div>}<div className="startup-actions"><button disabled={step===0} onClick={()=>setStep(value=>Math.max(0,value-1))}>Voltar</button>{step<6?<button className="primary" onClick={()=>setStep(value=>value+1)}>Continuar<ChevronRight/></button>:<button className="primary" disabled={!name.trim()} onClick={()=>void finish()}>Entrar no Jarvis</button>}</div></div></div>
}
