import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Activity, Brain, Check, Clock3, Download, ListTodo, Plus, SlidersHorizontal, Sparkles, Upload, X } from 'lucide-react'
import { api, jsonRequest } from '../services/api'
import type { ActivityItem, ContextEvidence, DocumentItem, Memory, Page, Task, ToolAction } from '../types'
import { Badge, Card, Empty, PageFrame, Row, formatDate, useLoad } from '../components/Common'

export function NowPage({ go }: { go: (page: Page) => void }) {
  const [tasks] = useLoad<Task[]>('/tasks', []); const [actions] = useLoad<ToolAction[]>('/tools/pending', []); const [activity] = useLoad<ActivityItem[]>('/activity', []); const [memories] = useLoad<Memory[]>('/memory', [])
  const date = new Intl.DateTimeFormat('pt-BR', { dateStyle: 'full', timeStyle: 'short' }).format(new Date())
  return <PageFrame eyebrow="Seu sistema pessoal" title="Agora" subtitle={date}><div className="hero"><div><span className="eyebrow">O QUE MERECE ATENÇÃO</span><h2>{tasks.some(item => !['done','cancelled'].includes(item.status)) ? 'Há itens esperando por você.' : 'Tudo sob controle por enquanto.'}</h2></div><button className="primary" onClick={() => go('chat')}><Sparkles/>Conversar com Jarvis</button></div><div className="grid two">
    <Card title="Tarefas prioritárias" icon={<ListTodo/>}>{tasks.some(item => item.status !== 'done') ? tasks.filter(item => item.status !== 'done').slice(0,5).map(item => <Row key={item.id} title={item.title} meta={`${item.priority} · ${item.status}`}/>) : <Empty title="Nada pendente" body="Tarefas reais aparecerão aqui."/>}</Card>
    <Card title="Aguardando confirmação" icon={<Clock3/>}>{actions.length ? actions.map(item => <Row key={item.action_id} title={item.tool} meta="Ação apenas proposta"/>) : <Empty title="Nenhuma ação pendente" body="O Jarvis pedirá sua autorização antes de escrever dados."/>}</Card>
    <Card title="Atividade recente" icon={<Activity/>}>{activity.length ? activity.slice(0,5).map(item => <Row key={item.id} title={item.tool} meta={item.status}/>) : <Empty title="Sem atividade" body="Execuções verificadas serão registradas aqui."/>}</Card>
    <Card title="Memórias recentes" icon={<Brain/>}>{memories.length ? memories.slice(0,5).map(item => <Row key={item.id} title={item.content} meta={item.category}/>) : <Empty title="Nenhuma memória registrada" body="Memória é separada do histórico de conversa."/>}</Card>
  </div></PageFrame>
}

const emptyMemory = { content: '', category: 'other', importance: 3, source_type: 'manual', source_reference: '' }
export function MemoryPage() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const path = `/memory${query ? `?query=${encodeURIComponent(query)}` : ''}`
  const [items, refresh] = useLoad<Memory[]>(path, []); const [draft, setDraft] = useState(emptyMemory); const [editing, setEditing] = useState<string>()
  const visible = category === 'all' ? items : items.filter(item => item.category === category)
  const save = async (event: FormEvent) => { event.preventDefault(); if (!draft.content.trim()) return; await api(editing ? `/memory/${editing}` : '/memory', jsonRequest(editing ? 'PUT' : 'POST', { ...draft, importance: Number(draft.importance) })); setDraft(emptyMemory); setEditing(undefined); refresh() }
  const edit = (item: Memory) => { setEditing(item.id); setDraft({ content: item.content, category: item.category, importance: item.importance, source_type: item.source_type, source_reference: item.source_reference || '' }) }
  return <PageFrame eyebrow="Contexto persistente" title="Memória" subtitle="Informações estruturadas; não é o histórico da conversa."><Card><form className="entity-form" onSubmit={save}><textarea value={draft.content} onChange={event => setDraft({...draft, content:event.target.value})} placeholder="Registre uma preferência, fato ou decisão…"/><select value={draft.category} onChange={event => setDraft({...draft, category:event.target.value})}><option value="other">Outro</option><option value="preference">Preferência</option><option value="person">Pessoa</option><option value="project">Projeto</option><option value="routine">Rotina</option><option value="fact">Fato</option><option value="instruction">Instrução</option><option value="decision">Decisão</option></select><label>Importância <input type="range" min="1" max="5" value={draft.importance} onChange={event => setDraft({...draft, importance:Number(event.target.value)})}/></label><div><button type="button" onClick={() => { setEditing(undefined); setDraft(emptyMemory) }}>Limpar</button><button className="primary"><Plus/>{editing ? 'Atualizar' : 'Salvar memória'}</button></div></form></Card><div className="filters"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Pesquisar memórias…"/><select value={category} onChange={event => setCategory(event.target.value)}><option value="all">Todas as categorias</option>{[...new Set(items.map(item => item.category))].map(item => <option key={item}>{item}</option>)}</select></div>{visible.length ? <div className="grid three">{visible.map(item => <Card key={item.id}><Badge>{item.category}</Badge><p className="item-copy">{item.content}</p><small>Importância {item.importance} · usada {formatDate(item.last_used_at)}</small><div className="entity-actions"><button onClick={() => edit(item)}>Editar</button><button className="danger-link" onClick={async () => { if (window.confirm('Excluir esta memória?')) { await api(`/memory/${item.id}`, {method:'DELETE'}); refresh() } }}>Excluir</button></div></Card>)}</div> : <Empty title="Nenhuma memória encontrada" body="Ajuste os filtros ou registre uma nova memória."/>}</PageFrame>
}

const emptyTask = { title:'', description:'', status:'inbox' as Task['status'], priority:'normal' as Task['priority'], due_at:'', project:'', estimated_minutes:'' }
export function TasksPage() {
  const [items, refresh] = useLoad<Task[]>('/tasks', []); const [filter, setFilter] = useState('open'); const [draft, setDraft] = useState(emptyTask); const [editing, setEditing] = useState<string>()
  const visible = items.filter(item => filter === 'all' || (filter === 'open' ? !['done','cancelled'].includes(item.status) : item.status === filter))
  const save = async (event: FormEvent) => { event.preventDefault(); if (!draft.title.trim()) return; const payload = {...draft, due_at:draft.due_at || null, project:draft.project || null, estimated_minutes:draft.estimated_minutes ? Number(draft.estimated_minutes) : null}; await api(editing ? `/tasks/${editing}` : '/tasks', jsonRequest(editing ? 'PUT':'POST', payload)); setDraft(emptyTask); setEditing(undefined); refresh() }
  const edit = (item: Task) => { setEditing(item.id); setDraft({title:item.title,description:item.description,status:item.status,priority:item.priority,due_at:item.due_at || '',project:item.project || '',estimated_minutes:item.estimated_minutes ? String(item.estimated_minutes):''}) }
  return <PageFrame eyebrow="Execução pessoal" title="Tarefas" subtitle="Inbox, planejamento e conclusão persistentes."><Card><form className="entity-form" onSubmit={save}><input value={draft.title} onChange={event => setDraft({...draft,title:event.target.value})} placeholder="Título da tarefa"/><textarea value={draft.description} onChange={event => setDraft({...draft,description:event.target.value})} placeholder="Descrição (opcional)"/><div className="form-grid"><select value={draft.status} onChange={event => setDraft({...draft,status:event.target.value as Task['status']})}>{['inbox','planned','doing','done','cancelled'].map(value => <option key={value}>{value}</option>)}</select><select value={draft.priority} onChange={event => setDraft({...draft,priority:event.target.value as Task['priority']})}>{['low','normal','high','critical'].map(value => <option key={value}>{value}</option>)}</select><input type="datetime-local" value={draft.due_at} onChange={event => setDraft({...draft,due_at:event.target.value})}/><input value={draft.project} onChange={event => setDraft({...draft,project:event.target.value})} placeholder="Projeto"/></div><div><button type="button" onClick={() => {setEditing(undefined);setDraft(emptyTask)}}>Limpar</button><button className="primary"><Plus/>{editing?'Atualizar':'Criar tarefa'}</button></div></form></Card><div className="filters"><select value={filter} onChange={event => setFilter(event.target.value)}><option value="open">Em aberto</option><option value="all">Todas</option>{['inbox','planned','doing','done','cancelled'].map(value => <option key={value}>{value}</option>)}</select></div>{visible.length ? <Card>{visible.map(item => <Row key={item.id} title={item.title} meta={`${item.priority} · ${item.status}${item.due_at ? ` · ${formatDate(item.due_at)}`:''}`} action={<div className="row-actions"><button onClick={() => edit(item)}>Editar</button>{item.status !== 'done' && <button title="Concluir" className="icon-button" onClick={async () => {await api(`/tasks/${item.id}`,jsonRequest('PUT',{...item,status:'done'}));refresh()}}><Check/></button>}<button className="danger-link" onClick={async()=>{if(window.confirm('Excluir esta tarefa?')){await api(`/tasks/${item.id}`,{method:'DELETE'});refresh()}}}>Excluir</button></div>}/>)}</Card>:<Empty title="Nada por aqui" body="Crie uma tarefa ou ajuste o filtro."/>}</PageFrame>
}

export function LibraryPage() { const [items,refresh]=useLoad<DocumentItem[]>('/library',[]); const [busy,setBusy]=useState(false); const upload=async(file?:File)=>{if(!file)return;setBusy(true);const body=new FormData();body.append('file',file);try{await api('/library',{method:'POST',body});refresh()}finally{setBusy(false)}}; return <PageFrame eyebrow="Knowledge vault local" title="Biblioteca" subtitle="PDF, DOCX, TXT e MD pesquisáveis por FTS5."><label className="dropzone"><Upload/><strong>{busy?'Processando…':'Adicionar arquivos'}</strong><span>Os arquivos permanecem neste computador. OCR ainda não está disponível.</span><input type="file" accept=".pdf,.docx,.txt,.md" onChange={event=>void upload(event.target.files?.[0])}/></label>{items.length?<Card>{items.map(item=><Row key={item.id} title={item.original_name} meta={`${item.type.toUpperCase()} · ${item.status} · ${item.chunk_count} trechos`} action={<button className="danger-link" onClick={async()=>{if(window.confirm('Remover este documento e seu índice?')){await api(`/library/${item.id}`,{method:'DELETE'});refresh()}}}>Excluir</button>}/>)}</Card>:<Empty title="Nenhum documento ainda" body="Adicione arquivos que você quer que o Jarvis consiga consultar."/>}</PageFrame> }

export function PersonaPage(){const[persona]=useLoad<{content:string}>('/persona',{content:''});const[content,setContent]=useState('');const[preview,setPreview]=useState('');const[saved,setSaved]=useState('');useEffect(()=>setContent(persona.content||''),[persona]);return <PageFrame eyebrow="Comportamento separado do código" title="Personalidade" subtitle="Edite as regras e faça uma inferência isolada antes de salvar."><div className="grid two"><Card title="Instruções da persona" icon={<SlidersHorizontal/>}><textarea className="editor" value={content} onChange={event=>setContent(event.target.value)}/><div className="actions"><button onClick={async()=>setPreview((await api<{message:string}>('/persona/preview',jsonRequest('POST',{content}))).message)}>Pré-visualizar</button><button className="primary" onClick={async()=>{await api('/persona',jsonRequest('PUT',{content}));setSaved('Salvo localmente.')}}>Salvar</button></div>{saved&&<small>{saved}</small>}</Card><Card title="Prévia isolada" icon={<Sparkles/>}>{preview?<div className="message assistant"><span>JARVIS DISSE</span><p>{preview}</p></div>:<Empty title="Sem prévia" body="A prévia não altera o histórico principal."/>}</Card></div></PageFrame>}

export function ActivityPage(){const[items]=useLoad<ActivityItem[]>('/activity',[]);const[status,setStatus]=useState('all');const[selected,setSelected]=useState<ActivityItem>();const visible=items.filter(item=>status==='all'||item.status===status);return <PageFrame eyebrow="Auditoria local" title="Atividade" subtitle="Toda ação real, bloqueada ou cancelada."><div className="filters"><select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Todos os estados</option>{['success','failed','blocked','cancelled'].map(value=><option key={value}>{value}</option>)}</select></div>{visible.length?<Card>{visible.map(item=><Row key={item.id} onClick={()=>setSelected(item)} title={item.tool} meta={`${item.status} · ${formatDate(item.timestamp)}`} action={<Badge tone={item.status==='success'?'success':item.status==='failed'?'danger':'neutral'}>{item.status}</Badge>}/>)}</Card>:<Empty title="Sem atividade" body="O log começará quando uma ação for executada."/>}{selected&&<aside className="detail-drawer"><button className="icon-button" onClick={()=>setSelected(undefined)}><X/></button><span className="eyebrow">DETALHES DA AÇÃO</span><h2>{selected.tool}</h2><Badge>{selected.status}</Badge><h3>Entrada</h3><pre>{JSON.stringify(selected.input,null,2)}</pre><h3>Resultado verificado</h3><pre>{JSON.stringify(selected.result,null,2)}</pre></aside>}</PageFrame>}

export function SystemPage({kind}:{kind:'settings'|'usage'|'devices'|'connections'}){const path=kind==='settings'?'/system':kind==='connections'?'/integrations':`/${kind}`;const[data,load,,error]=useLoad<unknown>(path,kind==='devices'||kind==='connections'?[]:{});const[backup,setBackup]=useState('');const titles={settings:'Configurações',usage:'Uso',devices:'Dispositivos',connections:'Conexões'};return <PageFrame eyebrow="Estado real" title={titles[kind]} subtitle="Sem dados fictícios ou serviços pagos."><Card>{error?<div className="chat-error"><span>{error}</span><button onClick={load}>Tentar novamente</button></div>:<pre className="data-view">{JSON.stringify(data,null,2)}</pre>}{kind==='settings'&&<div className="backup"><button className="primary" onClick={async()=>{const result=await api<{path:string;size_bytes:number}>('/backup',{method:'POST'});setBackup(`Backup criado: ${result.path} (${Math.ceil(result.size_bytes/1024)} KB)`)}}><Download/>Criar backup local</button>{backup&&<small>{backup}</small>}</div>}</Card></PageFrame>}
export function Placeholder({kind}:{kind:'calendar'|'automations'}){return <PageFrame eyebrow="Arquitetura preparada" title={kind==='calendar'?'Agenda':'Automações'} subtitle={kind==='calendar'?'Múltiplos calendários poderão ser conectados futuramente.':'Trigger + condição + ação, ainda sem engine de execução.'}><Empty title={kind==='calendar'?'Nenhum calendário conectado':'Nenhuma automação'} body={kind==='calendar'?'Conecte um calendário para visualizar seus compromissos aqui.':'A engine de automações será implementada em uma fase futura.'}/></PageFrame>}

export type { ContextEvidence }
