import type { ReactNode } from 'react'

export type Page = 'now' | 'core' | 'chat' | 'memory' | 'library' | 'tasks' | 'learning' | 'calendar' | 'automations' | 'connections' | 'persona' | 'devices' | 'activity' | 'usage' | 'settings'
export type NavItem = [Page, string, ReactNode]

export interface Conversation { id: string; title: string; created_at: string; updated_at: string }
export interface Message { id: string; role: 'user' | 'assistant' | 'system' | 'tool' | 'error'; content: string; created_at?: string; generation_status?: 'complete' | 'cancelled'; context?: ContextEvidence; feedback?: { rating: -1 | 1; correction?: string } }
export interface Memory { id: string; content: string; category: string; memory_type: string; status: 'candidate'|'active'|'superseded'|'archived'; confidence: number; importance: number; source_type: string; source_reference?: string; supersedes_id?: string; created_at: string; updated_at: string; last_used_at?: string }
export interface MemoryCandidate { id: string; content: string; category: string; memory_type: string; confidence: number; importance: number; dedupe_status: 'new'|'duplicate'|'similar'|'conflict'; related_memory_id?: string; created_at: string }
export interface Task { id: string; title: string; description: string; status: 'inbox' | 'planned' | 'doing' | 'done' | 'cancelled'; priority: 'low' | 'normal' | 'high' | 'critical'; due_at?: string; project?: string; estimated_minutes?: number; updated_at: string }
export interface DocumentItem { id: string; filename: string; original_name: string; type: string; status: string; chunk_count: number; size?: number; tags: string | string[]; description: string; use_for_rag: number | boolean; collection?: string }
export interface ContextDocument { document_id: string; filename: string; location?: string; relevant_text: string; score?: number }
export interface WebSource { source_id:string; title:string; url:string; domain:string; published_at?:string; retrieved_at:string; excerpt:string }
export interface ContextEvidence { memories?: Memory[]; documents?: ContextDocument[]; tasks?: Task[]; actions?: ToolAction[]; web?:{queries:Array<{query:string;searched_at?:string;redactions?:string[]}>;pages:Array<{source_id:string;title:string;url:string;domain:string;retrieved_at:string;truncated?:boolean}>;sources:WebSource[];used:string[]}; browser?:Array<{action:string;site:string;verified:boolean;status:string}>; conversation_summary?: { used: boolean; message_count: number }; agent_run_id?: string; agent_steps?: number; budget?: { max_chars: number; used_chars: number; estimated_tokens: number } }
export interface ToolAction { action_id: string; tool: string; input: Record<string, unknown>; status: string; id?: string; conversation_id?: string; created_at?: string; agent_run_id?: string }
export interface ActivityItem { id: string; tool: string; status: string; timestamp: string; input: Record<string, unknown>; result: Record<string, unknown> }
export interface SearchItem { type: string; id: string; path: string; title: string; subtitle?: string }
export interface Health { status: string; architecture?: string; app?: {status:string}; ollama?: {status:string}; model?: {status:string;name:string}; cognitive_events?: {status:string}; voice?: {status:string}; llm: { status?: string; model?: string; model_available?: boolean; error?: string } }
export interface ChatResult { conversation_id: string; message: string; message_id?: string; context: ContextEvidence; actions: ToolAction[]; agent_run_id?: string; agent_status?: string }
export interface StreamEvent { type: 'start' | 'token' | 'action' | 'done' | 'error'; conversation_id?: string; content?: string; message?: string; message_id?: string; context?: ContextEvidence; action?: ToolAction; actions?: ToolAction[]; agent_run_id?: string; agent_status?: string; memory_candidates?: MemoryCandidate[]; error?: { code: string; message: string } }

export type CognitiveState = 'IDLE' | 'THINKING' | 'SEARCHING_MEMORY' | 'SEARCHING_KNOWLEDGE' | 'SEARCHING_WEB' | 'BROWSING' | 'USING_TOOL' | 'WAITING_CONFIRMATION' | 'ERROR' | 'LISTENING' | 'TRANSCRIBING' | 'SPEAKING'
export interface VoiceProfile { profile_name:string; status:'REFERENCES_MISSING'|'NOT_BUILT'|'OUTDATED'|'BUILDING'|'READY'|'FAILED'; provider:string; reference_count:number; total_duration_seconds:number; fingerprint:string; language:string; worker:{status:string;stt?:{status:string};tts?:{status:string}}; voice_dna:Record<string,string> }
export interface VoiceStatus { active_sessions:number; vad:{status:string;provider:string}; resource_policy:Record<string,unknown>; privacy:{raw_microphone_saved:boolean;external_audio_transfer:boolean;transport:string}; worker:{status:string;stt?:{status:string};tts?:{status:string}}; profile:VoiceProfile; text_fallback:boolean }
export interface VoiceEvent { type:string; state?:CognitiveState; session_id?:string; turn_id?:string; text?:string; final?:boolean; audio?:string; mime_type?:string; message_id?:string; conversation_id?:string; action?:ToolAction; actions?:ToolAction[]; speech_text?:string; metadata?:Record<string,unknown>; error?:{code:string;message:string}; text_fallback?:boolean }
export type CognitiveNodeKind = 'core' | 'memory' | 'document' | 'task' | 'tool'
export type CognitiveQuality = 'AUTO' | 'HIGH' | 'MEDIUM' | 'LOW'
export interface CognitivePosition { x: number; y: number; z: number }
export interface CognitiveNode { id: string; entity_id?: string; kind: CognitiveNodeKind; cluster: string; label: string; position: CognitivePosition; size: number; intensity: number; metadata: Record<string, unknown> }
export interface CognitiveEdge { source: string; target: string; type: string; weight: number; connection_class?: 'memory_relationship'|'structural_connection'|'tool_connection'; evidence: { reason?: string; shared_terms?: string[]; same_category?: boolean; same_source?: boolean; similarity?: number; model?: string } }
export interface CognitiveCluster { id: string; center: CognitivePosition; count: number }
export interface CognitiveGraph { nodes: CognitiveNode[]; edges: CognitiveEdge[]; clusters: CognitiveCluster[]; state: { state: CognitiveState; last_event_id: number }; stats: { nodes: number; edges: number; memories: number; documents: number; tasks: number; tools: number; memory_relationships: number; structural_connections: number; tool_connections: number; relationship_provider: string } }
export interface CognitiveEvent { id: number; type: string; timestamp?: string; state: CognitiveState; payload: { node_id?: string; node_ids?: string[]; reason?: string; entity_id?: string; [key: string]: unknown } }
